### ISSUE TITLE
Cannot find the Resourcesanalysis dir

### ISSUE THREAD

**Issue by peiwithhao** [ZJU-SEC/AbstractResourceAttack#4]
I don't seem to see the ResourcesAnalysis folder in the project. Is this an abstract representation? I hope you can reply to me because this is very important to me.

**Comment by Yinwhe** [comment]
Sorry the README is quite old, we will update it.

**Comment by Yinwhe** [comment]
> I don't seem to see the ResourcesAnalysis folder in the project. Is this an abstract representation? I hope you can reply to me because this is very important to me.

Sorry the README is quite old, part of it are already not working. We will update it.

**Comment by Yinwhe** [comment]
> > I don't seem to see the ResourcesAnalysis folder in the project. Is this an abstract representation? I hope you can reply to me because this is very important to me.
> 
> Sorry the README is quite old, part of it are already not working. We will update it.

We have updated the README now.

**Comment by peiwithhao** [comment]
Thanks :)
